export type ContentTheme = "courage" | "kindness" | "friendship" | "wonder" | "imagination" | "comfort";
export type HeroId = "hero-1" | "hero-2" | "hero-3" | "hero-4" | "hero-5" | "hero-6" | "hero-7" | "hero-8";

export type StorySeed = {
  id: string;            // kebab-case
  title: string;         // 3-6 words, kid-friendly
  blurb: string;         // 1 sentence hook
  theme: ContentTheme;
  ageRange: "2-4" | "4-6" | "6-8" | "8-10";
  mode: "classic" | "madlibs" | "sleep";
  suggestedHeroId?: HeroId;
  setting?: string;
  tone?: string;
  sidekick?: string;
  problem?: string;
  emoji: string;         // single emoji as visual anchor
};

export const STORY_SEEDS: StorySeed[] = [
  // --- COURAGE (8 seeds) ---
  {
    id: "courage-pip-sunflower",
    title: "Pip and the Tall Sunflower",
    blurb: "A tiny mouse named Pip finds the courage to climb the tallest sunflower in the garden.",
    theme: "courage",
    ageRange: "2-4",
    mode: "classic",
    suggestedHeroId: "hero-5",
    setting: "enchanted-forest",
    tone: "gentle",
    sidekick: "none",
    problem: "help-friend",
    emoji: "🐭"
  },
  {
    id: "courage-nimbus-storm",
    title: "Nimbus and the Stormy Sky",
    blurb: "Nimbus the brave cloud helps a lost baby bird find its nest during a windy storm.",
    theme: "courage",
    ageRange: "4-6",
    mode: "classic",
    suggestedHeroId: "hero-5",
    setting: "enchanted-forest",
    tone: "adventurous",
    sidekick: "owl",
    problem: "help-friend",
    emoji: "⛈️"
  },
  {
    id: "courage-nova-caves",
    title: "Nova's Crystal Cave Search",
    blurb: "Nova guides her glowing star friend through a dark cavern to find the heart crystal.",
    theme: "courage",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-1",
    setting: "crystal-caves",
    tone: "mysterious",
    sidekick: "dragon",
    problem: "lost-treasure",
    emoji: "🛡️"
  },
  {
    id: "courage-whistle-mountain",
    title: "The Star Mountain Express",
    blurb: "Whistle must guide his magic train across a frozen mountain pass to deliver starglow mail.",
    theme: "courage",
    ageRange: "8-10",
    mode: "classic",
    suggestedHeroId: "hero-7",
    setting: "starship",
    tone: "adventurous",
    sidekick: "robot",
    problem: "ancient-puzzle",
    emoji: "🏔️"
  },
  {
    id: "courage-shadow-monster",
    title: "Shade's Midnight Shadow Game",
    blurb: "Shade shows a scared puppy that scary wall shadows are actually dancing trees.",
    theme: "courage",
    ageRange: "4-6",
    mode: "classic",
    suggestedHeroId: "hero-8",
    setting: "enchanted-forest",
    tone: "funny",
    sidekick: "bear",
    problem: "help-friend",
    emoji: "👻"
  },
  {
    id: "courage-deep-ocean",
    title: "Coral's Deep Sea Dive",
    blurb: "Coral dives into the dark blue ocean trench to guide a lost baby turtle home.",
    theme: "courage",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-2",
    setting: "underwater",
    tone: "adventurous",
    sidekick: "none",
    problem: "new-land",
    emoji: "🦈"
  },
  {
    id: "courage-luna-dark-dreams",
    title: "Luna and the Sleepy Badger",
    blurb: "Luna enters a mysterious dreamland to help a little badger face his fear of the dark.",
    theme: "courage",
    ageRange: "8-10",
    mode: "classic",
    suggestedHeroId: "hero-4",
    setting: "starship",
    tone: "mysterious",
    sidekick: "owl",
    problem: "missing-magic",
    emoji: "⚔️"
  },
  {
    id: "courage-quiet-hero",
    title: "The Bat Who Wanted Sunlight",
    blurb: "Shade helps a tiny sleepy bat learn that the night sky is cozy and full of stars.",
    theme: "courage",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-8",
    setting: "crystal-caves",
    tone: "gentle",
    emoji: "🧸"
  },

  // --- KINDNESS (8 seeds) ---
  {
    id: "kindness-coral-reef",
    title: "Coral Shares Her Sunset Shell",
    blurb: "Coral gives her favorite glowing seashell to a lonely sea star to brighten its home.",
    theme: "kindness",
    ageRange: "2-4",
    mode: "classic",
    suggestedHeroId: "hero-2",
    setting: "underwater",
    tone: "gentle",
    sidekick: "none",
    problem: "help-friend",
    emoji: "🐠"
  },
  {
    id: "kindness-bloom-garden",
    title: "Bloom's Silver Dream Seeds",
    blurb: "Bloom plants magical silver seeds that grow into beautiful flowers of pure happiness.",
    theme: "kindness",
    ageRange: "4-6",
    mode: "classic",
    suggestedHeroId: "hero-6",
    setting: "enchanted-forest",
    tone: "gentle",
    sidekick: "fairy",
    problem: "help-friend",
    emoji: "🌷"
  },
  {
    id: "kindness-orion-bridge",
    title: "Orion's Rainbow Starlight Bridge",
    blurb: "Orion builds a bridge of stars to help a stranded baby comet return to its parents.",
    theme: "kindness",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-3",
    setting: "starship",
    tone: "adventurous",
    sidekick: "robot",
    problem: "help-friend",
    emoji: "🤝"
  },
  {
    id: "kindness-nimbus-garden",
    title: "The Cloud and the Wilted Rose",
    blurb: "Nimbus gives his last raindrops to save a magical glowing rose in the star garden.",
    theme: "kindness",
    ageRange: "8-10",
    mode: "classic",
    suggestedHeroId: "hero-5",
    setting: "enchanted-forest",
    tone: "mysterious",
    sidekick: "owl",
    problem: "missing-magic",
    emoji: "🌦️"
  },
  {
    id: "kindness-barnaby-picnic",
    title: "Barnaby's Warm Honey Feast",
    blurb: "A friendly bear shares his sweet honey cakes with a family of sleepy squirrels.",
    theme: "kindness",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-8",
    setting: "enchanted-forest",
    tone: "gentle",
    emoji: "🍯"
  },
  {
    id: "kindness-fairy-wishes",
    title: "The Fairy's Giggly Wishing Well",
    blurb: "A cheerful fairy uses silly magic to make a sad badger laugh all night long.",
    theme: "kindness",
    ageRange: "4-6",
    mode: "madlibs",
    suggestedHeroId: "hero-6",
    setting: "enchanted-forest",
    tone: "funny",
    sidekick: "fairy",
    problem: "help-friend",
    emoji: "✨"
  },
  {
    id: "kindness-robot-healer",
    title: "Rusty and the Squeaky Gate",
    blurb: "Rusty the robot dog uses his gears to help fix a rusty gate for a woodland squirrel.",
    theme: "kindness",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-7",
    setting: "starship",
    tone: "adventurous",
    sidekick: "robot",
    problem: "help-friend",
    emoji: "🤖"
  },
  {
    id: "kindness-moon-tea",
    title: "Luna's Warm Moonlight Tea",
    blurb: "Luna brews chamomile tea with starlight to help the tired forest animals rest.",
    theme: "kindness",
    ageRange: "8-10",
    mode: "sleep",
    suggestedHeroId: "hero-4",
    setting: "starship",
    tone: "gentle",
    emoji: "☕"
  },

  // --- FRIENDSHIP (8 seeds) ---
  {
    id: "friendship-nova-orbit",
    title: "Nova and the Tiny Moon",
    blurb: "Nova guides a lonely baby planet into a safe, warm orbit around a friendly sun.",
    theme: "friendship",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-1",
    setting: "starship",
    tone: "gentle",
    emoji: "🪐"
  },
  {
    id: "friendship-orion-comet",
    title: "Orion's Cosmic Tag Game",
    blurb: "Orion plays tag with a speedy comet and learns how to share the space lanes.",
    theme: "friendship",
    ageRange: "4-6",
    mode: "classic",
    suggestedHeroId: "hero-3",
    setting: "starship",
    tone: "adventurous",
    sidekick: "robot",
    problem: "help-friend",
    emoji: "☄️"
  },
  {
    id: "friendship-bloom-woodland",
    title: "Bloom and the Treehouse Team",
    blurb: "Bloom brings a squirrel and a robin together to build a cozy, shared nest.",
    theme: "friendship",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-6",
    setting: "enchanted-forest",
    tone: "adventurous",
    sidekick: "bear",
    problem: "help-friend",
    emoji: "🐿️"
  },
  {
    id: "friendship-whale-song",
    title: "The Whale's Echo Song",
    blurb: "Coral and a group of singing sea whales solve a mystery under the oceanwaves.",
    theme: "friendship",
    ageRange: "8-10",
    mode: "classic",
    suggestedHeroId: "hero-2",
    setting: "underwater",
    tone: "mysterious",
    sidekick: "none",
    problem: "ancient-puzzle",
    emoji: "🐋"
  },
  {
    id: "friendship-silly-space",
    title: "The Cheese Planet Rocket",
    blurb: "Orion and a funny robot dog visit a moon that is made entirely of orange cheese.",
    theme: "friendship",
    ageRange: "4-6",
    mode: "madlibs",
    suggestedHeroId: "hero-3",
    setting: "starship",
    tone: "funny",
    sidekick: "robot",
    problem: "new-land",
    emoji: "🛸"
  },
  {
    id: "friendship-cave-puzzle",
    title: "Nova's Sparkling Light Link",
    blurb: "Nova and a wise old owl connect glowing crystals to open a secret cavern door.",
    theme: "friendship",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-1",
    setting: "crystal-caves",
    tone: "adventurous",
    sidekick: "owl",
    problem: "ancient-puzzle",
    emoji: "🧩"
  },
  {
    id: "friendship-milky-way",
    title: "Whistle's Sleeping Train Ride",
    blurb: "Whistle gathers all his forest friends for a quiet train ride along the Milky Way.",
    theme: "friendship",
    ageRange: "8-10",
    mode: "sleep",
    suggestedHeroId: "hero-7",
    setting: "starship",
    tone: "gentle",
    emoji: "🌌"
  },
  {
    id: "friendship-puppy-cuddle",
    title: "Shade's Cozy Cave Blanket",
    blurb: "Shade tucks a playful puppy into a soft shadow nest for a long night of sleep.",
    theme: "friendship",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-8",
    setting: "crystal-caves",
    tone: "gentle",
    emoji: "🐶"
  },

  // --- WONDER (8 seeds) ---
  {
    id: "wonder-luna-sky",
    title: "Luna Paints the Night Sky",
    blurb: "Luna weaves sparkling starlight into the dark sky to create the constellation of the horse.",
    theme: "wonder",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-4",
    setting: "starship",
    tone: "gentle",
    emoji: "🌌"
  },
  {
    id: "wonder-crystal-light",
    title: "The Rainbow Crystal Forest",
    blurb: "Nova finds a hidden cavern where the crystals glow and change colors when you hum.",
    theme: "wonder",
    ageRange: "4-6",
    mode: "classic",
    suggestedHeroId: "hero-1",
    setting: "crystal-caves",
    tone: "mysterious",
    sidekick: "fairy",
    problem: "lost-treasure",
    emoji: "💎"
  },
  {
    id: "wonder-bloom-flight",
    title: "Bloom and the Singing Butterfly",
    blurb: "Bloom follows a silver butterfly to a hidden valley where the flowers sing sweet lullabies.",
    theme: "wonder",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-6",
    setting: "enchanted-forest",
    tone: "adventurous",
    sidekick: "owl",
    problem: "new-land",
    emoji: "🦋"
  },
  {
    id: "wonder-space-sailor",
    title: "The Starship Starlight Sail",
    blurb: "Orion sails his starship through a gold space cloud that makes everyone float.",
    theme: "wonder",
    ageRange: "8-10",
    mode: "classic",
    suggestedHeroId: "hero-3",
    setting: "starship",
    tone: "adventurous",
    sidekick: "dragon",
    problem: "lost-treasure",
    emoji: "🚀"
  },
  {
    id: "wonder-firefly-dance",
    title: "The Firefly Constellation Show",
    blurb: "Bloom helps a group of fireflies build a glowing map of the night sky in the woods.",
    theme: "wonder",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-6",
    setting: "enchanted-forest",
    tone: "gentle",
    emoji: "🪰"
  },
  {
    id: "wonder-silly-mirror",
    title: "The Cloud's Funny Reflection",
    blurb: "Nimbus looks in a magic cave pool and sees himself wearing a crown of bubbles.",
    theme: "wonder",
    ageRange: "4-6",
    mode: "madlibs",
    suggestedHeroId: "hero-5",
    setting: "crystal-caves",
    tone: "funny",
    sidekick: "none",
    problem: "new-land",
    emoji: "🪞"
  },
  {
    id: "wonder-sea-castle",
    title: "The Shimmering Deep Palace",
    blurb: "Coral explores an ancient undersea castle made of glowing sea glass and pearls.",
    theme: "wonder",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-2",
    setting: "underwater",
    tone: "mysterious",
    sidekick: "dragon",
    problem: "lost-treasure",
    emoji: "🏰"
  },
  {
    id: "wonder-aurora-borealis",
    title: "Nova's Northern Light Show",
    blurb: "Nova waves her shield to paint the night sky with beautiful curtains of green light.",
    theme: "wonder",
    ageRange: "8-10",
    mode: "sleep",
    suggestedHeroId: "hero-1",
    setting: "starship",
    tone: "gentle",
    emoji: "✨"
  },

  // --- IMAGINATION (9 seeds) ---
  {
    id: "imagination-toy-alive",
    title: "The Shadow Bunny's Balloon",
    blurb: "Shade creates a shadow bunny who hops onto a starlight balloon to visit the moon.",
    theme: "imagination",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-8",
    setting: "enchanted-forest",
    tone: "gentle",
    emoji: "🎈"
  },
  {
    id: "imagination-cloud-shapes",
    title: "Nimbus the Cupcake Cloud",
    blurb: "Nimbus changes his shape into a giant fluffy cake and a friendly puppy dog.",
    theme: "imagination",
    ageRange: "4-6",
    mode: "classic",
    suggestedHeroId: "hero-5",
    setting: "enchanted-forest",
    tone: "funny",
    sidekick: "bear",
    problem: "new-land",
    emoji: "☁️"
  },
  {
    id: "imagination-rainbow-path",
    title: "Bloom's Sky-High Rainbow Bridge",
    blurb: "Bloom uses her silver wings to draw a bridge of rainbow dust across the starry lake.",
    theme: "imagination",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-6",
    setting: "enchanted-forest",
    tone: "adventurous",
    sidekick: "dragon",
    problem: "help-friend",
    emoji: "🌈"
  },
  {
    id: "imagination-milky-way-train",
    title: "The Milky Way Train Loops",
    blurb: "Whistle drives his train along a track that loops through the stars like a roller coaster.",
    theme: "imagination",
    ageRange: "8-10",
    mode: "classic",
    suggestedHeroId: "hero-7",
    setting: "starship",
    tone: "adventurous",
    sidekick: "robot",
    problem: "lost-treasure",
    emoji: "🚂"
  },
  {
    id: "imagination-candy-cloud",
    title: "Luna's Cotton Candy Dreams",
    blurb: "Luna weaves a dream of soft clouds that taste like sweet strawberries and honey.",
    theme: "imagination",
    ageRange: "4-6",
    mode: "sleep",
    suggestedHeroId: "hero-4",
    setting: "starship",
    tone: "gentle",
    emoji: "🍭"
  },
  {
    id: "imagination-madlibs-jungle",
    title: "The Singing Opera Monkeys",
    blurb: "Shade visits a funny forest where monkeys sing songs and trees grow jellybeans.",
    theme: "imagination",
    ageRange: "6-8",
    mode: "madlibs",
    suggestedHeroId: "hero-8",
    setting: "enchanted-forest",
    tone: "funny",
    sidekick: "fairy",
    problem: "new-land",
    emoji: "🌴"
  },
  {
    id: "imagination-magic-paint",
    title: "Nova's Glowing Star Brush",
    blurb: "Nova uses a starlight brush to bring bright colors back to a grey, sleeping valley.",
    theme: "imagination",
    ageRange: "8-10",
    mode: "classic",
    suggestedHeroId: "hero-1",
    setting: "crystal-caves",
    tone: "mysterious",
    sidekick: "owl",
    problem: "missing-magic",
    emoji: "🎨"
  },
  {
    id: "imagination-star-catcher",
    title: "Orion's Star Catching Game",
    blurb: "Orion catches tiny fallen stars in a silver bucket and hangs them back in the sky.",
    theme: "imagination",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-3",
    setting: "starship",
    tone: "gentle",
    emoji: "🪣"
  },
  {
    id: "imagination-silly-dino",
    title: "The Dino Who Forgot to Roar",
    blurb: "Nimbus helps a tiny baby dinosaur who makes funny squeaking bubble noises instead of roaring.",
    theme: "imagination",
    ageRange: "6-8",
    mode: "madlibs",
    suggestedHeroId: "hero-5",
    setting: "crystal-caves",
    tone: "funny",
    sidekick: "dragon",
    problem: "help-friend",
    emoji: "🦖"
  },

  // --- COMFORT (9 seeds) ---
  {
    id: "comfort-bedtime-train",
    title: "The Train to Sleepy Station",
    blurb: "Whistle plays a soft, slow whistle song as the train rolls into the Dreamland station.",
    theme: "comfort",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-7",
    setting: "starship",
    tone: "gentle",
    emoji: "🛌"
  },
  {
    id: "comfort-nimbus-blanket",
    title: "Nimbus wraps the Sleepy Deer",
    blurb: "Nimbus wraps a cold little deer in a warm, fluffy cloud blanket for a cozy nap.",
    theme: "comfort",
    ageRange: "4-6",
    mode: "sleep",
    suggestedHeroId: "hero-5",
    setting: "enchanted-forest",
    tone: "gentle",
    emoji: "☁️"
  },
  {
    id: "comfort-shade-camp",
    title: "The Cozy Shadow Campfire",
    blurb: "Shade makes a warm, glowing shadow fire and tells quiet bedtime stories to the forest animals.",
    theme: "comfort",
    ageRange: "6-8",
    mode: "classic",
    suggestedHeroId: "hero-8",
    setting: "crystal-caves",
    tone: "gentle",
    sidekick: "bear",
    problem: "help-friend",
    emoji: "⛺"
  },
  {
    id: "comfort-sleepy-reef",
    title: "The Ocean Heartbeat Song",
    blurb: "Coral listens to the deep ocean heartbeat that sings the entire coral reef to sleep.",
    theme: "comfort",
    ageRange: "8-10",
    mode: "sleep",
    suggestedHeroId: "hero-2",
    setting: "underwater",
    tone: "gentle",
    emoji: "🌊"
  },
  {
    id: "comfort-luna-lullaby",
    title: "Luna's Soft Starry Harp",
    blurb: "Luna plays her starlight harp to sing a sleepy, calming lullaby to the baby stars.",
    theme: "comfort",
    ageRange: "2-4",
    mode: "sleep",
    suggestedHeroId: "hero-4",
    setting: "starship",
    tone: "gentle",
    emoji: "🎶"
  },
  {
    id: "comfort-cozy-cave",
    title: "Nova's Warm Star Nightlight",
    blurb: "Nova sets her starlight shield to glow like a warm nightlight in the baby bear's cave.",
    theme: "comfort",
    ageRange: "4-6",
    mode: "sleep",
    suggestedHeroId: "hero-1",
    setting: "crystal-caves",
    tone: "gentle",
    emoji: "🕯️"
  },
  {
    id: "comfort-stardust-snack",
    title: "Cookies on the Night Train",
    blurb: "Whistle serves warm stardust cookies and hot milk on the sleeper car of the night train.",
    theme: "comfort",
    ageRange: "6-8",
    mode: "sleep",
    suggestedHeroId: "hero-7",
    setting: "starship",
    tone: "gentle",
    emoji: "🍪"
  },
  {
    id: "comfort-forest-bed",
    title: "Bloom's Cozy Moss Pillow",
    blurb: "Bloom tucks the baby woodland animals into a soft bed of green moss and flower petals.",
    theme: "comfort",
    ageRange: "8-10",
    mode: "sleep",
    suggestedHeroId: "hero-6",
    setting: "enchanted-forest",
    tone: "gentle",
    emoji: "🛌"
  },
  {
    id: "comfort-sloth-nap",
    title: "The Sleepy Sloth's Cradle",
    blurb: "Shade helps a slow-moving sloth find the perfect swinging branch for a peaceful nap.",
    theme: "comfort",
    ageRange: "4-6",
    mode: "sleep",
    suggestedHeroId: "hero-8",
    setting: "enchanted-forest",
    tone: "gentle",
    emoji: "🦥"
  }
];
