// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-concepts/Editorial.tsx": () => import("../components/mockups/landing-concepts/Editorial.tsx"),
  "./components/mockups/landing-concepts/Minimalist.tsx": () => import("../components/mockups/landing-concepts/Minimalist.tsx"),
  "./components/mockups/landing-concepts/Vibrant.tsx": () => import("../components/mockups/landing-concepts/Vibrant.tsx")
};
